name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - main  
      - staging
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    # Run actions action if actor is not andrijunaedi or aldycavalera
    if: ${{ (github.actor != 'andrijunaedi') && (github.actor != 'aldycavalera') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          VERCEL_PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tail -n 1)
          echo "url=$VERCEL_PREVIEW_URL" >> "$GITHUB_OUTPUT"

      - name: Create Vercel Preview Deployment Comment
        uses: actions/github-script@v7
        with:
          script: | 
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Preview deployment is ready! 🚀\n\n[Preview Deployment](${{ steps.deploy.outputs.url }})'
            })