name: Vercel Production Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Production
    # Run actions action if actor is not andrijunaedi or aldycavalera
    if: ${{ (github.actor != 'andrijunaedi') && (github.actor != 'aldycavalera') }}
    steps:
      - name: Trigger CURL Hook
        run: curl -X POST -d {} ${{ vars.VERCEL_DEPLOY_HOOK }}